### ISSUE TITLE
When I execute train_doc.py I encountered the following issues while working

### ISSUE THREAD

**Issue by water500ml** [visinf/cos-cvae#5]
Traceback (most recent call last):
  File "train_noc.py", line 186, in <module>
    for data in train_bar:
  File "/home/tuxiangsuo1502/miniconda3/envs/hjl/lib/python3.7/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/home/tuxiangsuo1502/miniconda3/envs/hjl/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/tuxiangsuo1502/miniconda3/envs/hjl/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/home/tuxiangsuo1502/miniconda3/envs/hjl/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/tuxiangsuo1502/miniconda3/envs/hjl/lib/python3.7/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/tuxiangsuo1502/miniconda3/envs/hjl/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/tuxiangsuo1502/miniconda3/envs/hjl/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/tuxiangsuo1502/miniconda3/envs/hjl/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/data/txs/hjl/coscvae/modules/data_loader_noc.py", line 263, in __getitem__
    caps = self.inv_annotations[str(image_idx)]
KeyError: "b'262146'"

How can it run normally? Thank you in advance for your reply

**Comment by s-mahajan** [comment]
Hi, you might need to convert the byte string to ASCII. 
https://stackoverflow.com/questions/6224052/what-is-the-difference-between-a-string-and-a-byte-string

Hope this helps!
